package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.AccessToken;
import com.airshiplay.official.mybatis.model.AccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int countByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int deleteByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int insert(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int insertSelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    List<AccessToken> selectByExample(AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    AccessToken selectByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccessToken record, @Param("example") AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccessToken record, @Param("example") AccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccessToken record);
}