package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgRoleAuthority;
import com.airshiplay.official.mybatis.model.CfgRoleAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int countByExample(CfgRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int deleteByExample(CfgRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int insert(CfgRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int insertSelective(CfgRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    List<CfgRoleAuthority> selectByExample(CfgRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    CfgRoleAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgRoleAuthority record, @Param("example") CfgRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgRoleAuthority record, @Param("example") CfgRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role_authority
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgRoleAuthority record);
}