package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgRole;
import com.airshiplay.official.mybatis.model.CfgRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int countByExample(CfgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int deleteByExample(CfgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int insert(CfgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int insertSelective(CfgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    List<CfgRole> selectByExample(CfgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    CfgRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgRole record, @Param("example") CfgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgRole record, @Param("example") CfgRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgRole record);
}