package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgThirdAccount;
import com.airshiplay.official.mybatis.model.CfgThirdAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgThirdAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int countByExample(CfgThirdAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int deleteByExample(CfgThirdAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int insert(CfgThirdAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int insertSelective(CfgThirdAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    List<CfgThirdAccount> selectByExample(CfgThirdAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgThirdAccount record, @Param("example") CfgThirdAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_third_account
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgThirdAccount record, @Param("example") CfgThirdAccountExample example);
}