package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgTags;
import com.airshiplay.official.mybatis.model.CfgTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int countByExample(CfgTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int deleteByExample(CfgTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int insert(CfgTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int insertSelective(CfgTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    List<CfgTags> selectByExample(CfgTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    CfgTags selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgTags record, @Param("example") CfgTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgTags record, @Param("example") CfgTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_tags
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgTags record);
}