package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgUserTag;
import com.airshiplay.official.mybatis.model.CfgUserTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgUserTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int countByExample(CfgUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int deleteByExample(CfgUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int insert(CfgUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int insertSelective(CfgUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    List<CfgUserTag> selectByExample(CfgUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    CfgUserTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgUserTag record, @Param("example") CfgUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgUserTag record, @Param("example") CfgUserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgUserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_tag
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgUserTag record);
}