package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgUserWechat;
import com.airshiplay.official.mybatis.model.CfgUserWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgUserWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int countByExample(CfgUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int deleteByExample(CfgUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int insert(CfgUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int insertSelective(CfgUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    List<CfgUserWechat> selectByExample(CfgUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    CfgUserWechat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgUserWechat record, @Param("example") CfgUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgUserWechat record, @Param("example") CfgUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_wechat
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgUserWechat record);
}