package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgUserRole;
import com.airshiplay.official.mybatis.model.CfgUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int countByExample(CfgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int deleteByExample(CfgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int insert(CfgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int insertSelective(CfgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    List<CfgUserRole> selectByExample(CfgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    CfgUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgUserRole record, @Param("example") CfgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgUserRole record, @Param("example") CfgUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user_role
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgUserRole record);
}