package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgUser;
import com.airshiplay.official.mybatis.model.CfgUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int countByExample(CfgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int deleteByExample(CfgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int insert(CfgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int insertSelective(CfgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    List<CfgUser> selectByExample(CfgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    CfgUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgUser record, @Param("example") CfgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgUser record, @Param("example") CfgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgUser record);
}