package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.CfgWechat;
import com.airshiplay.official.mybatis.model.CfgWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int countByExample(CfgWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int deleteByExample(CfgWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int insert(CfgWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int insertSelective(CfgWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    List<CfgWechat> selectByExample(CfgWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    CfgWechat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgWechat record, @Param("example") CfgWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgWechat record, @Param("example") CfgWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_wechat
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgWechat record);
}