package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.IpBsLb;
import com.airshiplay.official.mybatis.model.IpBsLbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IpBsLbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int countByExample(IpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int deleteByExample(IpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int insert(IpBsLb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int insertSelective(IpBsLb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    List<IpBsLb> selectByExample(IpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IpBsLb record, @Param("example") IpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_bs_lb
     * @mbggenerated
     */
    int updateByExample(@Param("record") IpBsLb record, @Param("example") IpBsLbExample example);
}