package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfAccessToken;
import com.airshiplay.official.mybatis.model.OfAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int countByExample(OfAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int deleteByExample(OfAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int deleteByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int insert(OfAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int insertSelective(OfAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    List<OfAccessToken> selectByExample(OfAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    OfAccessToken selectByPrimaryKey(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfAccessToken record, @Param("example") OfAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfAccessToken record, @Param("example") OfAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_access_token
     * @mbggenerated
     */
    int updateByPrimaryKey(OfAccessToken record);
}