package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfAuthority;
import com.airshiplay.official.mybatis.model.OfAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int countByExample(OfAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int deleteByExample(OfAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int insert(OfAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int insertSelective(OfAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    List<OfAuthority> selectByExample(OfAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    OfAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfAuthority record, @Param("example") OfAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfAuthority record, @Param("example") OfAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_authority
     * @mbggenerated
     */
    int updateByPrimaryKey(OfAuthority record);
}