package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfBusinessRealShop;
import com.airshiplay.official.mybatis.model.OfBusinessRealShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfBusinessRealShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int countByExample(OfBusinessRealShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int deleteByExample(OfBusinessRealShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int insert(OfBusinessRealShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int insertSelective(OfBusinessRealShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    List<OfBusinessRealShop> selectByExample(OfBusinessRealShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfBusinessRealShop record, @Param("example") OfBusinessRealShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_business_real_shop
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfBusinessRealShop record, @Param("example") OfBusinessRealShopExample example);
}