package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfCatalogDetail;
import com.airshiplay.official.mybatis.model.OfCatalogDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfCatalogDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int countByExample(OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int deleteByExample(OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int insert(OfCatalogDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int insertSelective(OfCatalogDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    List<OfCatalogDetail> selectByExampleWithBLOBs(OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    List<OfCatalogDetail> selectByExample(OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfCatalogDetail record, @Param("example") OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OfCatalogDetail record, @Param("example") OfCatalogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_catalog_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfCatalogDetail record, @Param("example") OfCatalogDetailExample example);
}