package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfCompany;
import com.airshiplay.official.mybatis.model.OfCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int countByExample(OfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int deleteByExample(OfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int insert(OfCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int insertSelective(OfCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    List<OfCompany> selectByExample(OfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    OfCompany selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfCompany record, @Param("example") OfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfCompany record, @Param("example") OfCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_company
     * @mbggenerated
     */
    int updateByPrimaryKey(OfCompany record);
}