package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfIpBsLb;
import com.airshiplay.official.mybatis.model.OfIpBsLbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfIpBsLbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int countByExample(OfIpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int deleteByExample(OfIpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int insert(OfIpBsLb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int insertSelective(OfIpBsLb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    List<OfIpBsLb> selectByExample(OfIpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfIpBsLb record, @Param("example") OfIpBsLbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfIpBsLb record, @Param("example") OfIpBsLbExample example);
}