package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfNewsCategory;
import com.airshiplay.official.mybatis.model.OfNewsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfNewsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int countByExample(OfNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int deleteByExample(OfNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int insert(OfNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int insertSelective(OfNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    List<OfNewsCategory> selectByExample(OfNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfNewsCategory record, @Param("example") OfNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_category
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfNewsCategory record, @Param("example") OfNewsCategoryExample example);
}