package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfNewsDetail;
import com.airshiplay.official.mybatis.model.OfNewsDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfNewsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int countByExample(OfNewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int deleteByExample(OfNewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int insert(OfNewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int insertSelective(OfNewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    List<OfNewsDetail> selectByExample(OfNewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfNewsDetail record, @Param("example") OfNewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_news_detail
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfNewsDetail record, @Param("example") OfNewsDetailExample example);
}