package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfPermission;
import com.airshiplay.official.mybatis.model.OfPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int countByExample(OfPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int deleteByExample(OfPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int insert(OfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int insertSelective(OfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    List<OfPermission> selectByExample(OfPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    OfPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfPermission record, @Param("example") OfPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfPermission record, @Param("example") OfPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_permission
     * @mbggenerated
     */
    int updateByPrimaryKey(OfPermission record);
}