package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfRoleAuthority;
import com.airshiplay.official.mybatis.model.OfRoleAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int countByExample(OfRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int deleteByExample(OfRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int insert(OfRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int insertSelective(OfRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    List<OfRoleAuthority> selectByExample(OfRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    OfRoleAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfRoleAuthority record, @Param("example") OfRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfRoleAuthority record, @Param("example") OfRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_authority
     * @mbggenerated
     */
    int updateByPrimaryKey(OfRoleAuthority record);
}