package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfRolePermission;
import com.airshiplay.official.mybatis.model.OfRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int countByExample(OfRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int deleteByExample(OfRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int insert(OfRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int insertSelective(OfRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    List<OfRolePermission> selectByExample(OfRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    OfRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfRolePermission record, @Param("example") OfRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfRolePermission record, @Param("example") OfRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_role_permission
     * @mbggenerated
     */
    int updateByPrimaryKey(OfRolePermission record);
}