package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfUserQq;
import com.airshiplay.official.mybatis.model.OfUserQqExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfUserQqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int countByExample(OfUserQqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int deleteByExample(OfUserQqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int insert(OfUserQq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int insertSelective(OfUserQq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    List<OfUserQq> selectByExample(OfUserQqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    OfUserQq selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfUserQq record, @Param("example") OfUserQqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfUserQq record, @Param("example") OfUserQqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfUserQq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_qq
     * @mbggenerated
     */
    int updateByPrimaryKey(OfUserQq record);
}