package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfUserRole;
import com.airshiplay.official.mybatis.model.OfUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int countByExample(OfUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int deleteByExample(OfUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int insert(OfUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int insertSelective(OfUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    List<OfUserRole> selectByExample(OfUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    OfUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfUserRole record, @Param("example") OfUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfUserRole record, @Param("example") OfUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_role
     * @mbggenerated
     */
    int updateByPrimaryKey(OfUserRole record);
}