package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.OfUserWechat;
import com.airshiplay.official.mybatis.model.OfUserWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfUserWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int countByExample(OfUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int deleteByExample(OfUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int insert(OfUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int insertSelective(OfUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    List<OfUserWechat> selectByExample(OfUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    OfUserWechat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfUserWechat record, @Param("example") OfUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfUserWechat record, @Param("example") OfUserWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfUserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_user_wechat
     * @mbggenerated
     */
    int updateByPrimaryKey(OfUserWechat record);
}