package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.QuSubject;
import com.airshiplay.official.mybatis.model.QuSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int countByExample(QuSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int deleteByExample(QuSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int insert(QuSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int insertSelective(QuSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    List<QuSubject> selectByExample(QuSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    QuSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuSubject record, @Param("example") QuSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuSubject record, @Param("example") QuSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject
     * @mbggenerated
     */
    int updateByPrimaryKey(QuSubject record);
}