package com.airshiplay.official.mybatis.mapper;

import com.airshiplay.official.mybatis.model.QuTopicAnswer;
import com.airshiplay.official.mybatis.model.QuTopicAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuTopicAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int countByExample(QuTopicAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int deleteByExample(QuTopicAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int insert(QuTopicAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int insertSelective(QuTopicAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    List<QuTopicAnswer> selectByExample(QuTopicAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuTopicAnswer record, @Param("example") QuTopicAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic_answer
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuTopicAnswer record, @Param("example") QuTopicAnswerExample example);
}