package com.airshiplay.official.mybatis.model;

import java.util.Date;

public class CfgAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_authority.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_authority.patient_id
     *
     * @mbggenerated
     */
    private Long patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_authority.authority_name
     *
     * @mbggenerated
     */
    private String authorityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_authority.authority_desc
     *
     * @mbggenerated
     */
    private String authorityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_authority.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_authority.id
     *
     * @return the value of cfg_authority.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_authority.id
     *
     * @param id the value for cfg_authority.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_authority.patient_id
     *
     * @return the value of cfg_authority.patient_id
     *
     * @mbggenerated
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_authority.patient_id
     *
     * @param patientId the value for cfg_authority.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_authority.authority_name
     *
     * @return the value of cfg_authority.authority_name
     *
     * @mbggenerated
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_authority.authority_name
     *
     * @param authorityName the value for cfg_authority.authority_name
     *
     * @mbggenerated
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_authority.authority_desc
     *
     * @return the value of cfg_authority.authority_desc
     *
     * @mbggenerated
     */
    public String getAuthorityDesc() {
        return authorityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_authority.authority_desc
     *
     * @param authorityDesc the value for cfg_authority.authority_desc
     *
     * @mbggenerated
     */
    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc == null ? null : authorityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_authority.create_time
     *
     * @return the value of cfg_authority.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_authority.create_time
     *
     * @param createTime the value for cfg_authority.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}