package com.airshiplay.official.mybatis.model;

import java.io.Serializable;

public class CfgArea implements Serializable {
    /**
     * 行政唯一标示
     * <p> 
     * database column <code>cfg_area.id</code>
     */
    private Integer id;

    /**
     * 名称（省、市、街道、小区 ）
     * <p> 
     * database column <code>cfg_area.name</code>
     */
    private String name;

    /**
     * 行政等级（1省、2市、3区）
     * <p> 
     * database column <code>cfg_area.level</code>
     */
    private Integer level;

    /**
     * 行政上级ID
     * <p> 
     * database column <code>cfg_area.upid</code>
     */
    private Integer upid;

    /**
     * 显示顺序
     * <p> 
     * database column <code>cfg_area.displayorder</code>
     */
    private Integer displayorder;

    /**
     * database column <code>cfg_area.full_name</code>
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_area
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取行政唯一标示
     *
     * @return id - 行政唯一标示
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置行政唯一标示
     *
     * @param id 行政唯一标示
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取名称（省、市、街道、小区 ）
     *
     * @return name - 名称（省、市、街道、小区 ）
     */
    public String getName() {
        return name;
    }

    /**
     * 设置名称（省、市、街道、小区 ）
     *
     * @param name 名称（省、市、街道、小区 ）
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取行政等级（1省、2市、3区）
     *
     * @return level - 行政等级（1省、2市、3区）
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置行政等级（1省、2市、3区）
     *
     * @param level 行政等级（1省、2市、3区）
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * 获取行政上级ID
     *
     * @return upid - 行政上级ID
     */
    public Integer getUpid() {
        return upid;
    }

    /**
     * 设置行政上级ID
     *
     * @param upid 行政上级ID
     */
    public void setUpid(Integer upid) {
        this.upid = upid;
    }

    /**
     * 获取显示顺序
     *
     * @return displayorder - 显示顺序
     */
    public Integer getDisplayorder() {
        return displayorder;
    }

    /**
     * 设置显示顺序
     *
     * @param displayorder 显示顺序
     */
    public void setDisplayorder(Integer displayorder) {
        this.displayorder = displayorder;
    }

    /**
     * @return full_name
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * @param fullName
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_area
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfgArea other = (CfgArea) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getUpid() == null ? other.getUpid() == null : this.getUpid().equals(other.getUpid()))
            && (this.getDisplayorder() == null ? other.getDisplayorder() == null : this.getDisplayorder().equals(other.getDisplayorder()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_area
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getUpid() == null) ? 0 : getUpid().hashCode());
        result = prime * result + ((getDisplayorder() == null) ? 0 : getDisplayorder().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_area
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", level=").append(level);
        sb.append(", upid=").append(upid);
        sb.append(", displayorder=").append(displayorder);
        sb.append(", fullName=").append(fullName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}