package com.airshiplay.official.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CfgAuthority implements Serializable {
    /**
     * database column <code>cfg_authority.id</code>
     */
    private Long id;

    /**
     * database column <code>cfg_authority.up_id</code>
     */
    private Long upId;

    /**
     * 权限名称
     * <p> 
     * database column <code>cfg_authority.authority_name</code>
     */
    private String authorityName;

    /**
     * 授权URL地址
     * <p> 
     * database column <code>cfg_authority.authority_url</code>
     */
    private String authorityUrl;

    /**
     * 权限描述
     * <p> 
     * database column <code>cfg_authority.authority_desc</code>
     */
    private String authorityDesc;

    /**
     * database column <code>cfg_authority.create_time</code>
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_authority
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return up_id
     */
    public Long getUpId() {
        return upId;
    }

    /**
     * @param upId
     */
    public void setUpId(Long upId) {
        this.upId = upId;
    }

    /**
     * 获取权限名称
     *
     * @return authority_name - 权限名称
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * 设置权限名称
     *
     * @param authorityName 权限名称
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * 获取授权URL地址
     *
     * @return authority_url - 授权URL地址
     */
    public String getAuthorityUrl() {
        return authorityUrl;
    }

    /**
     * 设置授权URL地址
     *
     * @param authorityUrl 授权URL地址
     */
    public void setAuthorityUrl(String authorityUrl) {
        this.authorityUrl = authorityUrl == null ? null : authorityUrl.trim();
    }

    /**
     * 获取权限描述
     *
     * @return authority_desc - 权限描述
     */
    public String getAuthorityDesc() {
        return authorityDesc;
    }

    /**
     * 设置权限描述
     *
     * @param authorityDesc 权限描述
     */
    public void setAuthorityDesc(String authorityDesc) {
        this.authorityDesc = authorityDesc == null ? null : authorityDesc.trim();
    }

    /**
     * @return create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_authority
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfgAuthority other = (CfgAuthority) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUpId() == null ? other.getUpId() == null : this.getUpId().equals(other.getUpId()))
            && (this.getAuthorityName() == null ? other.getAuthorityName() == null : this.getAuthorityName().equals(other.getAuthorityName()))
            && (this.getAuthorityUrl() == null ? other.getAuthorityUrl() == null : this.getAuthorityUrl().equals(other.getAuthorityUrl()))
            && (this.getAuthorityDesc() == null ? other.getAuthorityDesc() == null : this.getAuthorityDesc().equals(other.getAuthorityDesc()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_authority
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUpId() == null) ? 0 : getUpId().hashCode());
        result = prime * result + ((getAuthorityName() == null) ? 0 : getAuthorityName().hashCode());
        result = prime * result + ((getAuthorityUrl() == null) ? 0 : getAuthorityUrl().hashCode());
        result = prime * result + ((getAuthorityDesc() == null) ? 0 : getAuthorityDesc().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_authority
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", upId=").append(upId);
        sb.append(", authorityName=").append(authorityName);
        sb.append(", authorityUrl=").append(authorityUrl);
        sb.append(", authorityDesc=").append(authorityDesc);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}