package com.airshiplay.official.mybatis.model;

import java.io.Serializable;

public class CfgBanner implements Serializable {
    /**
     * database column <code>cfg_banner.id</code>
     */
    private Long id;

    /**
     * database column <code>cfg_banner.banner_width</code>
     */
    private Integer bannerWidth;

    /**
     * database column <code>cfg_banner.banner_height</code>
     */
    private Integer bannerHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_banner
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return banner_width
     */
    public Integer getBannerWidth() {
        return bannerWidth;
    }

    /**
     * @param bannerWidth
     */
    public void setBannerWidth(Integer bannerWidth) {
        this.bannerWidth = bannerWidth;
    }

    /**
     * @return banner_height
     */
    public Integer getBannerHeight() {
        return bannerHeight;
    }

    /**
     * @param bannerHeight
     */
    public void setBannerHeight(Integer bannerHeight) {
        this.bannerHeight = bannerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_banner
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfgBanner other = (CfgBanner) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBannerWidth() == null ? other.getBannerWidth() == null : this.getBannerWidth().equals(other.getBannerWidth()))
            && (this.getBannerHeight() == null ? other.getBannerHeight() == null : this.getBannerHeight().equals(other.getBannerHeight()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_banner
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBannerWidth() == null) ? 0 : getBannerWidth().hashCode());
        result = prime * result + ((getBannerHeight() == null) ? 0 : getBannerHeight().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_banner
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bannerWidth=").append(bannerWidth);
        sb.append(", bannerHeight=").append(bannerHeight);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}