package com.airshiplay.official.mybatis.model;

public class CfgBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_banner.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_banner.banner_width
     *
     * @mbggenerated
     */
    private Integer bannerWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_banner.banner_height
     *
     * @mbggenerated
     */
    private Integer bannerHeight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_banner.id
     *
     * @return the value of cfg_banner.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_banner.id
     *
     * @param id the value for cfg_banner.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_banner.banner_width
     *
     * @return the value of cfg_banner.banner_width
     *
     * @mbggenerated
     */
    public Integer getBannerWidth() {
        return bannerWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_banner.banner_width
     *
     * @param bannerWidth the value for cfg_banner.banner_width
     *
     * @mbggenerated
     */
    public void setBannerWidth(Integer bannerWidth) {
        this.bannerWidth = bannerWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_banner.banner_height
     *
     * @return the value of cfg_banner.banner_height
     *
     * @mbggenerated
     */
    public Integer getBannerHeight() {
        return bannerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_banner.banner_height
     *
     * @param bannerHeight the value for cfg_banner.banner_height
     *
     * @mbggenerated
     */
    public void setBannerHeight(Integer bannerHeight) {
        this.bannerHeight = bannerHeight;
    }
}