package com.airshiplay.official.mybatis.model;

public class CfgCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.zipcode
     *
     * @mbggenerated
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.site_title
     *
     * @mbggenerated
     */
    private String siteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.meta_keyword
     *
     * @mbggenerated
     */
    private String metaKeyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.meta_description
     *
     * @mbggenerated
     */
    private String metaDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.meta_author
     *
     * @mbggenerated
     */
    private String metaAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_company.favicon
     *
     * @mbggenerated
     */
    private String favicon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.id
     *
     * @return the value of cfg_company.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.id
     *
     * @param id the value for cfg_company.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.name
     *
     * @return the value of cfg_company.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.name
     *
     * @param name the value for cfg_company.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.address
     *
     * @return the value of cfg_company.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.address
     *
     * @param address the value for cfg_company.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.tel
     *
     * @return the value of cfg_company.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.tel
     *
     * @param tel the value for cfg_company.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.zipcode
     *
     * @return the value of cfg_company.zipcode
     *
     * @mbggenerated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.zipcode
     *
     * @param zipcode the value for cfg_company.zipcode
     *
     * @mbggenerated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.site_title
     *
     * @return the value of cfg_company.site_title
     *
     * @mbggenerated
     */
    public String getSiteTitle() {
        return siteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.site_title
     *
     * @param siteTitle the value for cfg_company.site_title
     *
     * @mbggenerated
     */
    public void setSiteTitle(String siteTitle) {
        this.siteTitle = siteTitle == null ? null : siteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.meta_keyword
     *
     * @return the value of cfg_company.meta_keyword
     *
     * @mbggenerated
     */
    public String getMetaKeyword() {
        return metaKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.meta_keyword
     *
     * @param metaKeyword the value for cfg_company.meta_keyword
     *
     * @mbggenerated
     */
    public void setMetaKeyword(String metaKeyword) {
        this.metaKeyword = metaKeyword == null ? null : metaKeyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.meta_description
     *
     * @return the value of cfg_company.meta_description
     *
     * @mbggenerated
     */
    public String getMetaDescription() {
        return metaDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.meta_description
     *
     * @param metaDescription the value for cfg_company.meta_description
     *
     * @mbggenerated
     */
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription == null ? null : metaDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.meta_author
     *
     * @return the value of cfg_company.meta_author
     *
     * @mbggenerated
     */
    public String getMetaAuthor() {
        return metaAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.meta_author
     *
     * @param metaAuthor the value for cfg_company.meta_author
     *
     * @mbggenerated
     */
    public void setMetaAuthor(String metaAuthor) {
        this.metaAuthor = metaAuthor == null ? null : metaAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_company.favicon
     *
     * @return the value of cfg_company.favicon
     *
     * @mbggenerated
     */
    public String getFavicon() {
        return favicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_company.favicon
     *
     * @param favicon the value for cfg_company.favicon
     *
     * @mbggenerated
     */
    public void setFavicon(String favicon) {
        this.favicon = favicon == null ? null : favicon.trim();
    }
}