package com.airshiplay.official.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class CfgUser implements Serializable {
    /**
     * database column <code>cfg_user.id</code>
     */
    private Long id;

    /**
     * database column <code>cfg_user.nickname</code>
     */
    private String nickname;

    /**
     * database column <code>cfg_user.username</code>
     */
    private String username;

    /**
     * database column <code>cfg_user.email</code>
     */
    private String email;

    /**
     * database column <code>cfg_user.mobile</code>
     */
    private String mobile;

    /**
     * database column <code>cfg_user.password</code>
     */
    private String password;

    /**
     * database column <code>cfg_user.salt</code>
     */
    private String salt;

    /**
     * 1
     * <p> 
     * database column <code>cfg_user.create_time</code>
     */
    private Date createTime;

    /**
     * database column <code>cfg_user.reg_ip</code>
     */
    private String regIp;

    /**
     * database column <code>cfg_user.reg_uid</code>
     */
    private Long regUid;

    /**
     * database column <code>cfg_user.latest_login_time</code>
     */
    private Date latestLoginTime;

    /**
     * database column <code>cfg_user.latest_login_ip</code>
     */
    private String latestLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_user
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return nickname
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * @param nickname
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * @return username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * @return mobile
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * @return password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * @return salt
     */
    public String getSalt() {
        return salt;
    }

    /**
     * @param salt
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * 获取1
     *
     * @return create_time - 1
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置1
     *
     * @param createTime 1
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return reg_ip
     */
    public String getRegIp() {
        return regIp;
    }

    /**
     * @param regIp
     */
    public void setRegIp(String regIp) {
        this.regIp = regIp == null ? null : regIp.trim();
    }

    /**
     * @return reg_uid
     */
    public Long getRegUid() {
        return regUid;
    }

    /**
     * @param regUid
     */
    public void setRegUid(Long regUid) {
        this.regUid = regUid;
    }

    /**
     * @return latest_login_time
     */
    public Date getLatestLoginTime() {
        return latestLoginTime;
    }

    /**
     * @param latestLoginTime
     */
    public void setLatestLoginTime(Date latestLoginTime) {
        this.latestLoginTime = latestLoginTime;
    }

    /**
     * @return latest_login_ip
     */
    public String getLatestLoginIp() {
        return latestLoginIp;
    }

    /**
     * @param latestLoginIp
     */
    public void setLatestLoginIp(String latestLoginIp) {
        this.latestLoginIp = latestLoginIp == null ? null : latestLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfgUser other = (CfgUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getRegIp() == null ? other.getRegIp() == null : this.getRegIp().equals(other.getRegIp()))
            && (this.getRegUid() == null ? other.getRegUid() == null : this.getRegUid().equals(other.getRegUid()))
            && (this.getLatestLoginTime() == null ? other.getLatestLoginTime() == null : this.getLatestLoginTime().equals(other.getLatestLoginTime()))
            && (this.getLatestLoginIp() == null ? other.getLatestLoginIp() == null : this.getLatestLoginIp().equals(other.getLatestLoginIp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getRegIp() == null) ? 0 : getRegIp().hashCode());
        result = prime * result + ((getRegUid() == null) ? 0 : getRegUid().hashCode());
        result = prime * result + ((getLatestLoginTime() == null) ? 0 : getLatestLoginTime().hashCode());
        result = prime * result + ((getLatestLoginIp() == null) ? 0 : getLatestLoginIp().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_user
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nickname=").append(nickname);
        sb.append(", username=").append(username);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", createTime=").append(createTime);
        sb.append(", regIp=").append(regIp);
        sb.append(", regUid=").append(regUid);
        sb.append(", latestLoginTime=").append(latestLoginTime);
        sb.append(", latestLoginIp=").append(latestLoginIp);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}