package com.airshiplay.official.mybatis.model;

import java.io.Serializable;

public class CfgWebSite implements Serializable {
    /**
     * database column <code>cfg_web_site.id</code>
     */
    private Long id;

    /**
     * database column <code>cfg_web_site.name</code>
     */
    private String name;

    /**
     * database column <code>cfg_web_site.address</code>
     */
    private String address;

    /**
     * database column <code>cfg_web_site.tel</code>
     */
    private String tel;

    /**
     * database column <code>cfg_web_site.zipcode</code>
     */
    private String zipcode;

    /**
     * database column <code>cfg_web_site.site_title</code>
     */
    private String siteTitle;

    /**
     * database column <code>cfg_web_site.meta_keyword</code>
     */
    private String metaKeyword;

    /**
     * database column <code>cfg_web_site.meta_description</code>
     */
    private String metaDescription;

    /**
     * database column <code>cfg_web_site.meta_author</code>
     */
    private String metaAuthor;

    /**
     * 网站-favicon.ico
     * <p> 
     * database column <code>cfg_web_site.site_favicon</code>
     */
    private String siteFavicon;

    /**
     * database column <code>cfg_web_site.site_icp</code>
     */
    private String siteIcp;

    /**
     * 网站域名
     * <p> 
     * database column <code>cfg_web_site.site_domain</code>
     */
    private String siteDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cfg_web_site
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * @return tel
     */
    public String getTel() {
        return tel;
    }

    /**
     * @param tel
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * @return zipcode
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * @param zipcode
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * @return site_title
     */
    public String getSiteTitle() {
        return siteTitle;
    }

    /**
     * @param siteTitle
     */
    public void setSiteTitle(String siteTitle) {
        this.siteTitle = siteTitle == null ? null : siteTitle.trim();
    }

    /**
     * @return meta_keyword
     */
    public String getMetaKeyword() {
        return metaKeyword;
    }

    /**
     * @param metaKeyword
     */
    public void setMetaKeyword(String metaKeyword) {
        this.metaKeyword = metaKeyword == null ? null : metaKeyword.trim();
    }

    /**
     * @return meta_description
     */
    public String getMetaDescription() {
        return metaDescription;
    }

    /**
     * @param metaDescription
     */
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription == null ? null : metaDescription.trim();
    }

    /**
     * @return meta_author
     */
    public String getMetaAuthor() {
        return metaAuthor;
    }

    /**
     * @param metaAuthor
     */
    public void setMetaAuthor(String metaAuthor) {
        this.metaAuthor = metaAuthor == null ? null : metaAuthor.trim();
    }

    /**
     * 获取网站-favicon.ico
     *
     * @return site_favicon - 网站-favicon.ico
     */
    public String getSiteFavicon() {
        return siteFavicon;
    }

    /**
     * 设置网站-favicon.ico
     *
     * @param siteFavicon 网站-favicon.ico
     */
    public void setSiteFavicon(String siteFavicon) {
        this.siteFavicon = siteFavicon == null ? null : siteFavicon.trim();
    }

    /**
     * @return site_icp
     */
    public String getSiteIcp() {
        return siteIcp;
    }

    /**
     * @param siteIcp
     */
    public void setSiteIcp(String siteIcp) {
        this.siteIcp = siteIcp == null ? null : siteIcp.trim();
    }

    /**
     * 获取网站域名
     *
     * @return site_domain - 网站域名
     */
    public String getSiteDomain() {
        return siteDomain;
    }

    /**
     * 设置网站域名
     *
     * @param siteDomain 网站域名
     */
    public void setSiteDomain(String siteDomain) {
        this.siteDomain = siteDomain == null ? null : siteDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_web_site
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfgWebSite other = (CfgWebSite) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getZipcode() == null ? other.getZipcode() == null : this.getZipcode().equals(other.getZipcode()))
            && (this.getSiteTitle() == null ? other.getSiteTitle() == null : this.getSiteTitle().equals(other.getSiteTitle()))
            && (this.getMetaKeyword() == null ? other.getMetaKeyword() == null : this.getMetaKeyword().equals(other.getMetaKeyword()))
            && (this.getMetaDescription() == null ? other.getMetaDescription() == null : this.getMetaDescription().equals(other.getMetaDescription()))
            && (this.getMetaAuthor() == null ? other.getMetaAuthor() == null : this.getMetaAuthor().equals(other.getMetaAuthor()))
            && (this.getSiteFavicon() == null ? other.getSiteFavicon() == null : this.getSiteFavicon().equals(other.getSiteFavicon()))
            && (this.getSiteIcp() == null ? other.getSiteIcp() == null : this.getSiteIcp().equals(other.getSiteIcp()))
            && (this.getSiteDomain() == null ? other.getSiteDomain() == null : this.getSiteDomain().equals(other.getSiteDomain()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_web_site
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getZipcode() == null) ? 0 : getZipcode().hashCode());
        result = prime * result + ((getSiteTitle() == null) ? 0 : getSiteTitle().hashCode());
        result = prime * result + ((getMetaKeyword() == null) ? 0 : getMetaKeyword().hashCode());
        result = prime * result + ((getMetaDescription() == null) ? 0 : getMetaDescription().hashCode());
        result = prime * result + ((getMetaAuthor() == null) ? 0 : getMetaAuthor().hashCode());
        result = prime * result + ((getSiteFavicon() == null) ? 0 : getSiteFavicon().hashCode());
        result = prime * result + ((getSiteIcp() == null) ? 0 : getSiteIcp().hashCode());
        result = prime * result + ((getSiteDomain() == null) ? 0 : getSiteDomain().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_web_site
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", tel=").append(tel);
        sb.append(", zipcode=").append(zipcode);
        sb.append(", siteTitle=").append(siteTitle);
        sb.append(", metaKeyword=").append(metaKeyword);
        sb.append(", metaDescription=").append(metaDescription);
        sb.append(", metaAuthor=").append(metaAuthor);
        sb.append(", siteFavicon=").append(siteFavicon);
        sb.append(", siteIcp=").append(siteIcp);
        sb.append(", siteDomain=").append(siteDomain);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}