package com.airshiplay.official.mybatis.model;

public class OfCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.catalog_name
     *
     * @mbggenerated
     */
    private String catalogName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.upid
     *
     * @mbggenerated
     */
    private Long upid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_catalog.url_path
     *
     * @mbggenerated
     */
    private String urlPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.id
     *
     * @return the value of of_catalog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.id
     *
     * @param id the value for of_catalog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.catalog_name
     *
     * @return the value of of_catalog.catalog_name
     *
     * @mbggenerated
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.catalog_name
     *
     * @param catalogName the value for of_catalog.catalog_name
     *
     * @mbggenerated
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName == null ? null : catalogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.remark
     *
     * @return the value of of_catalog.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.remark
     *
     * @param remark the value for of_catalog.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.seq
     *
     * @return the value of of_catalog.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.seq
     *
     * @param seq the value for of_catalog.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.status
     *
     * @return the value of of_catalog.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.status
     *
     * @param status the value for of_catalog.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.upid
     *
     * @return the value of of_catalog.upid
     *
     * @mbggenerated
     */
    public Long getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.upid
     *
     * @param upid the value for of_catalog.upid
     *
     * @mbggenerated
     */
    public void setUpid(Long upid) {
        this.upid = upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.type
     *
     * @return the value of of_catalog.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.type
     *
     * @param type the value for of_catalog.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.level
     *
     * @return the value of of_catalog.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.level
     *
     * @param level the value for of_catalog.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_catalog.url_path
     *
     * @return the value of of_catalog.url_path
     *
     * @mbggenerated
     */
    public String getUrlPath() {
        return urlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_catalog.url_path
     *
     * @param urlPath the value for of_catalog.url_path
     *
     * @mbggenerated
     */
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath == null ? null : urlPath.trim();
    }
}