package com.airshiplay.official.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class OfIpBsLb implements Serializable {
    /**
     * database column <code>of_ip_bs_lb.id</code>
     */
    private Long id;

    /**
     * database column <code>of_ip_bs_lb.ip</code>
     */
    private String ip;

    /**
     * database column <code>of_ip_bs_lb.country</code>
     */
    private String country;

    /**
     * database column <code>of_ip_bs_lb.country_code</code>
     */
    private String countryCode;

    /**
     * database column <code>of_ip_bs_lb.province</code>
     */
    private String province;

    /**
     * database column <code>of_ip_bs_lb.city</code>
     */
    private String city;

    /**
     * database column <code>of_ip_bs_lb.city_code</code>
     */
    private String cityCode;

    /**
     * 区/县
     * <p> 
     * database column <code>of_ip_bs_lb.district</code>
     */
    private String district;

    /**
     * database column <code>of_ip_bs_lb.street_number</code>
     */
    private String streetNumber;

    /**
     * 街道
     * <p> 
     * database column <code>of_ip_bs_lb.street</code>
     */
    private String street;

    /**
     * database column <code>of_ip_bs_lb.address</code>
     */
    private String address;

    /**
     * 纬度
     * <p> 
     * database column <code>of_ip_bs_lb.lat</code>
     */
    private String lat;

    /**
     * 经度
     * <p> 
     * database column <code>of_ip_bs_lb.lng</code>
     */
    private String lng;

    /**
     * database column <code>of_ip_bs_lb.operator</code>
     */
    private String operator;

    /**
     * 数据提供者
     * <p> 
     * database column <code>of_ip_bs_lb.provider</code>
     */
    private String provider;

    /**
     * 小区号
     * <p> 
     * database column <code>of_ip_bs_lb.lac</code>
     */
    private Integer lac;

    /**
     * 基站号\基站号(bid)
     * <p> 
     * database column <code>of_ip_bs_lb.cellid</code>
     */
    private Integer cellid;

    /**
     * 移动基站：0 联通基站:1 电信基站
     * <p> 
     * database column <code>of_ip_bs_lb.mnc</code>
     */
    private Integer mnc;

    /**
     * SID系统识别码（各地区一个）
     * <p> 
     * database column <code>of_ip_bs_lb.sid</code>
     */
    private Integer sid;

    /**
     * NID网络识别码（各地区1-3个）
     * <p> 
     * database column <code>of_ip_bs_lb.nid</code>
     */
    private Integer nid;

    /**
     * database column <code>of_ip_bs_lb.create_time</code>
     */
    private Date createTime;

    /**
     * database column <code>of_ip_bs_lb.uuid</code>
     */
    private String uuid;

    /**
     * 设备来源
     * <p> 
     * database column <code>of_ip_bs_lb.model</code>
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return ip
     */
    public String getIp() {
        return ip;
    }

    /**
     * @param ip
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * @return country
     */
    public String getCountry() {
        return country;
    }

    /**
     * @param country
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * @return country_code
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * @param countryCode
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * @return province
     */
    public String getProvince() {
        return province;
    }

    /**
     * @param province
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * @return city
     */
    public String getCity() {
        return city;
    }

    /**
     * @param city
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * @return city_code
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * @param cityCode
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * 获取区/县
     *
     * @return district - 区/县
     */
    public String getDistrict() {
        return district;
    }

    /**
     * 设置区/县
     *
     * @param district 区/县
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * @return street_number
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * @param streetNumber
     */
    public void setStreetNumber(String streetNumber) {
        this.streetNumber = streetNumber == null ? null : streetNumber.trim();
    }

    /**
     * 获取街道
     *
     * @return street - 街道
     */
    public String getStreet() {
        return street;
    }

    /**
     * 设置街道
     *
     * @param street 街道
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取纬度
     *
     * @return lat - 纬度
     */
    public String getLat() {
        return lat;
    }

    /**
     * 设置纬度
     *
     * @param lat 纬度
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * 获取经度
     *
     * @return lng - 经度
     */
    public String getLng() {
        return lng;
    }

    /**
     * 设置经度
     *
     * @param lng 经度
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * @return operator
     */
    public String getOperator() {
        return operator;
    }

    /**
     * @param operator
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * 获取数据提供者
     *
     * @return provider - 数据提供者
     */
    public String getProvider() {
        return provider;
    }

    /**
     * 设置数据提供者
     *
     * @param provider 数据提供者
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * 获取小区号
     *
     * @return lac - 小区号
     */
    public Integer getLac() {
        return lac;
    }

    /**
     * 设置小区号
     *
     * @param lac 小区号
     */
    public void setLac(Integer lac) {
        this.lac = lac;
    }

    /**
     * 获取基站号\基站号(bid)
     *
     * @return cellid - 基站号\基站号(bid)
     */
    public Integer getCellid() {
        return cellid;
    }

    /**
     * 设置基站号\基站号(bid)
     *
     * @param cellid 基站号\基站号(bid)
     */
    public void setCellid(Integer cellid) {
        this.cellid = cellid;
    }

    /**
     * 获取移动基站：0 联通基站:1 电信基站
     *
     * @return mnc - 移动基站：0 联通基站:1 电信基站
     */
    public Integer getMnc() {
        return mnc;
    }

    /**
     * 设置移动基站：0 联通基站:1 电信基站
     *
     * @param mnc 移动基站：0 联通基站:1 电信基站
     */
    public void setMnc(Integer mnc) {
        this.mnc = mnc;
    }

    /**
     * 获取SID系统识别码（各地区一个）
     *
     * @return sid - SID系统识别码（各地区一个）
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * 设置SID系统识别码（各地区一个）
     *
     * @param sid SID系统识别码（各地区一个）
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * 获取NID网络识别码（各地区1-3个）
     *
     * @return nid - NID网络识别码（各地区1-3个）
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * 设置NID网络识别码（各地区1-3个）
     *
     * @param nid NID网络识别码（各地区1-3个）
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * @return create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return uuid
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * @param uuid
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * 获取设备来源
     *
     * @return model - 设备来源
     */
    public String getModel() {
        return model;
    }

    /**
     * 设置设备来源
     *
     * @param model 设备来源
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OfIpBsLb other = (OfIpBsLb) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getStreetNumber() == null ? other.getStreetNumber() == null : this.getStreetNumber().equals(other.getStreetNumber()))
            && (this.getStreet() == null ? other.getStreet() == null : this.getStreet().equals(other.getStreet()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()))
            && (this.getLng() == null ? other.getLng() == null : this.getLng().equals(other.getLng()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getProvider() == null ? other.getProvider() == null : this.getProvider().equals(other.getProvider()))
            && (this.getLac() == null ? other.getLac() == null : this.getLac().equals(other.getLac()))
            && (this.getCellid() == null ? other.getCellid() == null : this.getCellid().equals(other.getCellid()))
            && (this.getMnc() == null ? other.getMnc() == null : this.getMnc().equals(other.getMnc()))
            && (this.getSid() == null ? other.getSid() == null : this.getSid().equals(other.getSid()))
            && (this.getNid() == null ? other.getNid() == null : this.getNid().equals(other.getNid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getModel() == null ? other.getModel() == null : this.getModel().equals(other.getModel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getStreetNumber() == null) ? 0 : getStreetNumber().hashCode());
        result = prime * result + ((getStreet() == null) ? 0 : getStreet().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        result = prime * result + ((getLng() == null) ? 0 : getLng().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getProvider() == null) ? 0 : getProvider().hashCode());
        result = prime * result + ((getLac() == null) ? 0 : getLac().hashCode());
        result = prime * result + ((getCellid() == null) ? 0 : getCellid().hashCode());
        result = prime * result + ((getMnc() == null) ? 0 : getMnc().hashCode());
        result = prime * result + ((getSid() == null) ? 0 : getSid().hashCode());
        result = prime * result + ((getNid() == null) ? 0 : getNid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getModel() == null) ? 0 : getModel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table of_ip_bs_lb
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", country=").append(country);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", district=").append(district);
        sb.append(", streetNumber=").append(streetNumber);
        sb.append(", street=").append(street);
        sb.append(", address=").append(address);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", operator=").append(operator);
        sb.append(", provider=").append(provider);
        sb.append(", lac=").append(lac);
        sb.append(", cellid=").append(cellid);
        sb.append(", mnc=").append(mnc);
        sb.append(", sid=").append(sid);
        sb.append(", nid=").append(nid);
        sb.append(", createTime=").append(createTime);
        sb.append(", uuid=").append(uuid);
        sb.append(", model=").append(model);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}