package com.airshiplay.official.mybatis.model;

import java.io.Serializable;

public class QuSubjectAnswer implements Serializable {
    /**
     * database column <code>qu_subject_answer.id</code>
     */
    private Long id;

    /**
     * database column <code>qu_subject_answer.uid</code>
     */
    private Long uid;

    /**
     * 题目主键
     * <p> 
     * database column <code>qu_subject_answer.subject_id</code>
     */
    private Long subjectId;

    /**
     * 选项答案
     * <p> 
     * database column <code>qu_subject_answer.option_no</code>
     */
    private String optionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qu_subject_answer
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return uid
     */
    public Long getUid() {
        return uid;
    }

    /**
     * @param uid
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * 获取题目主键
     *
     * @return subject_id - 题目主键
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * 设置题目主键
     *
     * @param subjectId 题目主键
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * 获取选项答案
     *
     * @return option_no - 选项答案
     */
    public String getOptionNo() {
        return optionNo;
    }

    /**
     * 设置选项答案
     *
     * @param optionNo 选项答案
     */
    public void setOptionNo(String optionNo) {
        this.optionNo = optionNo == null ? null : optionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject_answer
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuSubjectAnswer other = (QuSubjectAnswer) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getOptionNo() == null ? other.getOptionNo() == null : this.getOptionNo().equals(other.getOptionNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject_answer
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getOptionNo() == null) ? 0 : getOptionNo().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_subject_answer
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", optionNo=").append(optionNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}