package com.airshiplay.official.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class QuTopic implements Serializable {
    /**
     * database column <code>qu_topic.id</code>
     */
    private Long id;

    /**
     * 话题类型，1、统计类话题；2、
     * <p> 
     * database column <code>qu_topic.type</code>
     */
    private Integer type;

    /**
     * 话题标题
     * <p> 
     * database column <code>qu_topic.title</code>
     */
    private String title;

    /**
     * 1、审核；2、上线
     * <p> 
     * database column <code>qu_topic.status</code>
     */
    private Integer status;

    /**
     * 创建时间
     * <p> 
     * database column <code>qu_topic.create_time</code>
     */
    private Date createTime;

    /**
     * 创建人
     * <p> 
     * database column <code>qu_topic.create_uid</code>
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qu_topic
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取话题类型，1、统计类话题；2、
     *
     * @return type - 话题类型，1、统计类话题；2、
     */
    public Integer getType() {
        return type;
    }

    /**
     * 设置话题类型，1、统计类话题；2、
     *
     * @param type 话题类型，1、统计类话题；2、
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 获取话题标题
     *
     * @return title - 话题标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置话题标题
     *
     * @param title 话题标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取1、审核；2、上线
     *
     * @return status - 1、审核；2、上线
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 设置1、审核；2、上线
     *
     * @param status 1、审核；2、上线
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取创建时间
     *
     * @return create_time - 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取创建人
     *
     * @return create_uid - 创建人
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * 设置创建人
     *
     * @param createUid 创建人
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuTopic other = (QuTopic) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUid() == null ? other.getCreateUid() == null : this.getCreateUid().equals(other.getCreateUid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUid() == null) ? 0 : getCreateUid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qu_topic
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", title=").append(title);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUid=").append(createUid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}